### ISSUE TITLE
Cannot find module 'react-chartjs-2'

### ISSUE THREAD

**Issue by donibehrami** [jerairrest/react-chartjs-2#142]
Any idea why this might be happening, I really love these charts and would like to use them. Tried deleting node_modules and reinstall them, clearing npm cache and some other things. I see that it is available in node_modules, whole files and folders. A suggestion would be great. Btw im using typescript. I saw the d.ts files but I still get the error. Thnx
![module](https://user-images.githubusercontent.com/28535698/27044441-df8e5c78-4f9d-11e7-8c6b-5b910422dbf7.png)

**Comment by gentgaashi** [comment]
This happens when compiling with --module=es2015. Probably an issue with the declaration file.

**Comment by gentgaashi** [comment]
Setting moduleResolution to 'node' should fix it also. Because when using module es2015 the moduleResolution will default to "Classic", so you need to manually set it to 'node'. From typescript compiler options docs:

moduleResolution = module === "AMD" | "System" | "ES6" ? "Classic" : "Node"

They should just make it always default to node tbh, since classic is just a leftover from old ts and is there just for backward compatibility issues.

**Comment by jerairrest** [comment]
Thanks @gentgaashi for answering this. I am closing for now
