### ISSUE TITLE
How to add custom chart plugin?

### ISSUE THREAD

**Issue by iTechKnow** [jerairrest/react-chartjs-2#246]
I want to add a CandleStick chart type by using this plugin: https://github.com/chartjs/chartjs-chart-financial

I don't know how to integrate the CandleStick plugin into react-chartjs-2.  Is it possible to achieve this?

**Comment by robin-pham** [comment]
Hi @iTechKnow, it's very possible! You just have to import the library and it'll be available for use. It'll automatically register with the global Chart.js instance the moment you import it.

For example, in the root of your React app you can have:

```
import 'chartjs-chart-financial';
import React from 'react';
import {render} from 'react-dom';
```

In your specific case, since `chartjs-chart-financial` isn't available as a npm module, you can install it directly from git using:
`npm install --save https://github.com/chartjs/chartjs-chart-financial.git` or use `yarn add` if you prefer.

Now you can use this chart type with `ChartComponent`.

Example: 
```
import React from 'react';
import ChartComponent from 'react-chartjs-2';

class Candlestick extends React.Component {
  render() {
    return (
      <ChartComponent
        {...this.props} 
        type="candlestick"
      />
    );
  }
}
```

**Comment by VLechuk-SoftServeInc** [comment]
Doesn't seem to work now(

**Comment by Jak3b0** [comment]
Hi,

I'm trying to use the 'chartjs-plugin-stacked100' but can't make it work. 

1. I installed the plugin using `yarn install chartjs-plugin-stacked100`
2. I'm importing it like this: `import 'chartjs-plugin-stacked100';`
3. I added the `plugins` section in the chart options like this: 
```
  plugins: {
    stacked100: { enabled: true }
  }
```
4. And I'm passing the options to the `Line` chart like this:
```
<Line data={chartData} options={chartOptions} />
```

Any idea?

**Comment by titulus** [comment]
@Jak3b0 
> 3. I added the `plugins` section in the chart options like this:

[`plugins`](https://www.chartjs.org/docs/latest/developers/plugins.html) - is not a part of [`options`](https://www.chartjs.org/docs/latest/getting-started/)

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.

**Comment by raevillena** [comment]
if we are using webpack, does the code at sandbox still equates to it? cause at webpack, there lots of difference even with es6
