### ISSUE TITLE
redraw bool property ignored - IE11 issue

### ISSUE THREAD

**Issue by tfrailey** [jerairrest/react-chartjs-2#420]
When pushing new data into components using IE11, I consistently get an error `SCRIPT438: Object doesn't support property or method 'values'` during the re-render.  In looking around, it appears this is within the destroyChart method `var datasets = Object.values(this.datasets);`. This method should only fire if the prop redraw is true (default is false), during componentDidUpdate (among other places), however it still seems to fire regardless. I've also tried passing an explicit `redraw={false}` with the component, but with no luck.
If I just set datasets to an empty object, or basically do anything other than Object.values, I get no errors in IE.

Initial rendering is fine, this is only an issue on update.  Thanks!

**Comment by skauffmann** [comment]
I had the same problem since Object.values is not supported by IE11.
You can add support for this method by using react-app-polyfill and adding the following lines to your index.js
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';

Full documentation: https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill
